apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
spec:
  replicas: 10
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
      - name: items
        image: ghcr.io/mdmsft/items:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: items
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.18.0.100
  selector:
    app: items
  ports:
  - port: 80
    targetPort: 80
